version: "3.7"

services:

  postgres:
    container_name: 'blog-app-postgres'
    image: 'postgres:14.2'
    restart: always
    ports:
      - '5000:5000'
    environment:
      - 'POSTGRES_USER=ademola'
      - 'POSTGRES_DB=blog_app'
      - 'POSTGRES_PASSWORD=passthewordaround'
    command: -p 5000

